# Parameters for detection, particularly for MOT challenge public detections.
detection:
    score_thresh: 0.0  # detection score threshold below which to discard.
    overlap_thresh: 0.30 # overlap threshold for suppressing unnecessary boxes using non-maximum suppression(NMS).
    display_detections: False

# Parameters for tracking
tracking:
    motion_model_type: cv   # cv for constant velocity, rw for random walk
    MOT_data_type: 'MOT16'  # Set to 'MOT16', 'MOT17-DPM', 'MOT17-FRCNN', 'MOT17-SDP', 'MOT20', 'HiEve' or 'DanceTrack'.

    train_test_type: 'train'  # Set to 'train' or to 'test'
    is_DanceTrack_val: False  # Set to True for DanceTrack validation or to False for DanceTrack train
    experiment_name: 'GMPHD1' # The name of the experiment, used for running different experiments and then evaluations,
    # e.g. GMPHD1, GMPHD2, etc.

    similarity_threshold: 0.2  # For data association (0.2 gives better result than 0.4)
    prediction_time_threshold: 3  # 5, 10 #  After this time of predictions, don't save and display the track information
    track_kill_time_threshold: 3  # 2#3#5#15 # After this time of predictions, kill the track
    track_min_length: 0  #4 #5 # Minimum number track time steps before it becomes reliable to be saved and displayed. In
    # the PHD filter, this can be neglected as the filter is robust to clutter that causes short-lived tracks.

    appearance_weight: 0.65  # 0.9  # Appearance weight i.e. motion (spatio-temporal) weight = 1 - appearance_weight
    window_ReId: 2000
    reid_threshold: 0.2  # 0.2 (better) #0.3  # threshold for reid (lower will require greater similarity)

    feature_extraction_stage_type: False  # Set to True for extracting features from estimates or to False for extracting
    # features from observations (detections) which also allows augmented likelihood at the update step.
    is_batch_feature_extraction: True  # Set to True for batch (of images) feature extraction or to False for single image
    # feature extraction.

    use_Jmax: True  # Set to True if you want to use J_max or to False for not using it.
    use_iou: False  # Set to True if you want to use IOU or to False for using bounding-box-normalize absolute distance.
    is_AddOn_prediction: True   # Set to True for using Add-On prediction.
    include_appearance: True  # Set to True if you want to include appearance features in addition to motion information
    # for track-to-estimate association.

    include_ReId: True   # Set to True for using ReId or to False for not using ReId.
    display_tracks: True
    display_trajectories: False
    save_tracked_frames: False

#    directories:
#        base_data: './data'
#        base_result: './result'


